name: Schedule Job Scrapper

on:
  schedule:
    - cron: '30 11 * * *'
  workflow_dispatch: 

jobs:
  run-scrapper:
    runs-on: ubuntu-latest
    environment: scrapper

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Decode LinkedIn Cookies
        run: |
          echo "${{ secrets.LINKEDIN_COOKIES_B64 }}" | base64 -d > linkedin_cookies.json

      - name: Run LinkedIn Job Scraper
        run: |
          python -m custom_job_collector.main
    
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/linkedin_job_scraper.log