name: Test Email

on:
  workflow_dispatch: 

jobs:
  test-email:
    runs-on: ubuntu-latest
    environment: scrapper

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Send Email
        env:
            FROM_EMAIL: ${{ vars.FROM_EMAIL }}
            SMTP_PORT: ${{ vars.SMTP_PORT }}
            SMTP_SERVER: ${{ vars.SMTP_SERVER }}
            SMTP_USER: ${{ vars.SMTP_USER }}
            TO_EMAIL: ${{ vars.TO_EMAIL }}
            USER_EMAIL: ${{ vars.USER_EMAIL }}
            SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
            USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: |
          python -m custom_job_collector.lib.email_handler